// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AntigravityController from "./antigravity_controller"
application.register("antigravity", AntigravityController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import CursorController from "./cursor_controller"
application.register("cursor", CursorController)

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MicroInteractionsController from "./micro_interactions_controller"
application.register("micro-interactions", MicroInteractionsController)

import PreloaderController from "./preloader_controller"
application.register("preloader", PreloaderController)

import ScrollRevealController from "./scroll_reveal_controller"
application.register("scroll-reveal", ScrollRevealController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import TypographyController from "./typography_controller"
application.register("typography", TypographyController)
