// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AntigravityController from "./antigravity_controller"
application.register("antigravity", AntigravityController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import HamburgerController from "./hamburger_controller"
application.register("hamburger", HamburgerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ScrollRevealController from "./scroll_reveal_controller"
application.register("scroll-reveal", ScrollRevealController)
